
/**
 * Calculator-agnostic "shareable report" contract.
 *
 * Every calculator (BMI today, 200+ more later) maps its own result into this
 * one shape. Nothing calculator-specific lives here or in the generators that
 * consume it — a calculator only ever builds a `ShareableReport` object; it
 * never draws pixels or PDF content itself.
 */

export interface ReportRow {
  /** Left-hand label, e.g. "Ideal Weight Range" */
  label: string;
  /** Right-hand value, e.g. "60.1 – 80.9 kg" */
  value: string;
}

export interface ReportSection {
  /** Optional sub-heading above this group of rows, e.g. "Waist Metrics" */
  heading?: string;
  rows: ReportRow[];
  /**
   * Visual category for card-based renderers (currently the PDF only).
   * 'input'  -> neutral/slate card, tagged "INPUT" — what the user typed in.
   * 'output' -> accent-tinted card, tagged "RESULT" — calculated values.
   * Defaults to 'output' when omitted.
   */
  variant?: 'input' | 'output';
}

export interface ShareableReport {
  /** Small eyebrow label in the header, e.g. "BMI RESULT" */
  title: string;
  /** Large headline value, e.g. "23.4" */
  headlineValue: string;
  /** Status/category shown under the headline, e.g. "Normal range" */
  headlineLabel: string;
  /** Hex color (e.g. "#22c55e") driving the header/accent color in both outputs */
  accentColor: string;
  /** Up to 3 short lines shown top-right of the header, e.g. ["WHO Standard", "Metric Units"] */
  meta?: string[];
  /** One or more groups of label/value rows, rendered in order */
  sections: ReportSection[];
  /**
   * Optional extra sections that appear ONLY in the PDF ("Complete Report"),
   * never in the quick shareable PNG image — e.g. a "Your Inputs" section.
   * Rendered after `sections`, in the same label/value row style. Omit this
   * field entirely for calculators that don't need an inputs recap.
   */
  pdfOnlySections?: ReportSection[];
  /**
   * Optional override of `sections` used ONLY by the PNG image. Use this when
   * `sections` includes something long/reference-table-like (e.g. every
   * possible category band) that's valuable in a paginated PDF but makes a
   * "quick share" image needlessly tall — the image already shows the
   * matched category via `headlineLabel`. Falls back to `sections` when
   * omitted, so existing calculators are unaffected. The PDF always uses the
   * full `sections` (plus `pdfOnlySections`), never this field.
   */
  imageSections?: ReportSection[];
  /** Optional footer disclaimer, e.g. "For informational purposes only — not medical advice." */
  disclaimer?: string;
  /** Filename stem (no extension) used for both downloads, e.g. "bmi-result" */
  fileNameBase: string;
}

/**
 * App-wide site attribution shown in the footer of a downloaded report, e.g.
 * "Generated by CalculoX at calculox.com". Deliberately NOT part of
 * ShareableReport: calculators only ever describe calculation data, never
 * site branding. Whatever screen triggers the download (currently
 * calculators/[slug]/client.tsx) builds this once from the same site
 * settings used everywhere else in the app and passes it to the generators.
 */
export interface SiteInfo {
  name: string;
  url: string;
}
